server:
  port: 9090

spring:
  application:
    name: zuul
  config:
    name: zuul
	
zuul:
  routes:
    accounting:
      path:/accounting/**
      serviceId:accounting
    authenticate:
      path:/authenticate/**
      serviceId:authenticate
    authorize:
      path:/authorize/**
      serviceId:authorize